package com.personal.jobagent.discovery;
import org.springframework.stereotype.Service; import java.util.*;
@Service public class ExtractionComparisonService {
 public record FieldComparison(String field,Object left,Object right,boolean agreement,double confidence){}
 public record ComparisonResult(List<FieldComparison> fields,boolean agreement,boolean needsVerification,double confidence,Map<String,Object> decision){public ComparisonResult{fields=List.copyOf(fields);decision=Map.copyOf(decision);}}
 private static final List<String> F=List.of("title","company","location","remoteType","salary","employmentType","description","skills","applicationUrl","sourceUrl","externalJobId");
 public ComparisonResult compare(ScraperProvider.ExtractedJob a,ScraperProvider.ExtractedJob b,double threshold){List<FieldComparison> out=new ArrayList<>();int conflicts=0;for(String f:F){Object x=value(a,f),y=value(b,f);boolean eq=norm(x,f).equals(norm(y,f));if(!eq)conflicts++;out.add(new FieldComparison(f,x,y,eq,eq?1.0:((x==null||y==null)?.5:(f.equals("description")||f.equals("skills")?.75:0.0))));}double c=out.stream().mapToDouble(FieldComparison::confidence).average().orElse(0);boolean identityConflict=out.stream().anyMatch(f->!f.agreement()&&Set.of("title","company","location","applicationUrl","externalJobId").contains(f.field()));return new ComparisonResult(out,conflicts==0,identityConflict||(conflicts>0&&(1-c)>=threshold),c,Map.of("conflicts",conflicts,"decision",conflicts==0?"AGREED":"VERIFY_OR_REVIEW"));}
 private static Object value(ScraperProvider.ExtractedJob j,String f){return switch(f){case "title"->j.title();case "company"->j.company();case "location"->j.location();case "remoteType"->j.remoteType();case "salary"->j.salary();case "employmentType"->j.employmentType();case "description"->j.description();case "skills"->j.skills();case "applicationUrl"->j.applicationUrl();case "sourceUrl"->j.sourceUrl();case "externalJobId"->j.externalJobId();default->null;};}
 private static String norm(Object v,String f){if(v==null)return "";if(v instanceof Collection<?> c)return c.stream().map(String::valueOf).map(String::toLowerCase).sorted().toList().toString();String s=String.valueOf(v).trim().replaceAll("\\s+"," ").toLowerCase(Locale.ROOT);return f.equals("description")?s.replaceAll("[^a-z0-9 ]",""):s;}
}
