package com.personal.jobagent.llm;

public enum TaskType {
    JOB_DESCRIPTION_ANALYSIS,
    JOB_CLASSIFICATION,
    SPONSORSHIP_ANALYSIS,
    SKILL_EXTRACTION,
    SKILL_MATCHING,
    CV_TAILORING,
    COVER_LETTER,
    APPLICATION_QA,
    TECHNICAL_REASONING,
    LARGE_CONTEXT,
    HIGH_VOLUME_EXTRACTION,
    EMAIL_CLASSIFICATION
}
